### ISSUE TITLE
is there a set() function?

### ISSUE THREAD

**Issue by dalemcbeath** [NitrofMtl/MicroTuple#1]
Hi, NitrofMtl,  

Thanks for the arduino library, it was just the perfect thing I was looking for.     

I am using the mTuple  as an array, and was wondering if there will be a set() to go along with the get()?  Or if there is a simple way to change the contents of a mTuple once created?  I'm new to the idea of Tuples, so I could be missing something elementry.

I'm building an array like this (works fine):

```
MicroTuple <byte, byte, const char *, byte, const char *, int, int, int>  grid [27] = {
    // row col    color      id     name        min   max   val
    //
    {   0,  2,  "#EBEBEB",  0x00, "head_LR"  ,  -90,   90,   0 },  // row 0
    {   1,  2,  "#EBEBEB",  0x00, "head_UD"  ,  -90,   90,   0 },  // row 1
    
    {   2,  0,  "#900000",  0x02, "arm_IO"   ,  -90,   90,   0 },  // row 2
    {   2,  1,  "#900000",  0x01, "shldr_FB" ,  -90,   90,   0 },
    {   2,  2,  "#EBEBEB",  0x00, "body"     ,  -90,   90,   0 },
    {   2,  3,  "#509050",  0x04, "shldr_FB" ,  -90,   90,   0 },
    {   2,  4,  "#509050",  0x05, "arm_IO"   ,  -90,   90,   0 },
    
    {   3,  0,  "#900000",  0x07, "elbow_IO" ,  -90,   90,   0 },   // row 3
    {   3,  2,  "#EBEBEB",  0x00, "body"     ,  -90,   90,   0 },
    {   3,  4,  "#509050",  0x0C, "elbow_IO" ,  -90,   90,   0 },
    
    {   4,  0,  "#EBEBEB",  0x00, "hand_TW"  ,  -90,   90,   0 },   // row 4
    {   4,  1,  "#B00000",  0x07, "leg_IO"   ,  -90,   90,   0 },   
    {   4,  2,  "#EBEBEB",  0x00, "body"     ,  -90,   90,   0 },
    {   4,  3,  "#50B050",  0x0D, "leg_IO"   ,  -90,   90,   0 },  
    {   4,  4,  "#EBEBEB",  0x00, "hand_TW"  ,  -90,   90,   0 },
    
    {   5,  0,  "#EBEBEB",  0x00, "hand_UD"  ,  -90,   90,   0 },   // row 5
    {   5,  1,  "#B00000",  0x11, "leg_TW"   ,  -90,   90,   0 },   // LS servo ID 17 0x11
    {   5,  3,  "#50B050",  0x12, "leg_TW"   ,  -90,   90,   0 },   // LS servo ID 18 0x12
    {   5,  4,  "#EBEBEB",  0x00, "hand_UD"  ,  -90,   90,   0 },
    
    {   6,  1,  "#B00000",  0x08, "leg_FB"   ,  -90,   90,   0 },   // row 6
    {   6,  3,  "#50B050",  0x0D, "leg_FB"   ,  -90,   90,   0 },
    
    {   7,  1,  "#D05050",  0x09, "knee_FB"  ,  -90,   90,   0 },   // row 7
    {   7,  3,  "#80D080",  0x0E, "knee_FB"  ,  -90,   90,   0 },
    
    {   8,  1,  "#A02020",  0x0A, "ankle_UD" ,  -90,   90,   0 },   // row 8
    {   8,  3,  "#408040",  0x0F, "ankle_UD" ,  -90,   90,   0 },
    
    {   9,  1,  "#A02020",  0x0B, "foot_TW"  ,  -90,   90,   0 },   // row 9
    {   9,  3,  "#408040",  0x10, "foot_TW"  ,  -90,   90,   0 }                                
};
```

and get data from the array like this:

`byte id    = grid[5].get<3>();`

which works as expected.  

Is there a way to put data back into the mTuple, say

` grid[5].set<3>( newValue );`

thanks for your time, 

dm

**Comment by NitrofMtl** [comment]
could be an idea. I will try to find some time soon.

But in other hand, I don't know the context where you use this data but, have you consider to simply use array of struct ? That will be the simpler solution in normal usage... 

Regards.


Nitrof

**Comment by dalemcbeath** [comment]
Thank you for your time and answer. I'm new to c++ and find it very restrictive in many ways, though I understand why it's used for small memory processors.  I will do research today on an array of structs, which I've never heard of, but hey, I hadn't heard of tuples until a few days ago either - lockdown gives me a lot of time to learn. 

application is generation of a web page from a server on an ESP32 using arduino IDE to code.

Thank you again for what I must say looks like an elegant solution to mixed type arrays in c++, and for getting back to me with an answer and suggestion on another direction.  Much appreciated!

dale

**Comment by dalemcbeath** [comment]
Thanks for the 'array of structs' suggestion, that works perfectly, and with little change in code.

Very much appreciated, 

dale
